server:
  port: 9000
spring:
  application:
    name: zuul-geteway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
zuul:
  routes:
    employee:
      service-id: springcloud-feign
      path: /zuul-emp/**   # 替换微服务名称
  ignored-services: '*' # 禁止使用微服务名称访问 *号代表所有微服务名都不行
  prefix: /maomi  # 前缀，加在path（/zuul-emp）前面